apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: gcr.io/gdg-microservices-project/email-service:latest
          env:
            - name: MAILGUN_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mailgun-secret
                  key: MAILGUN_DOMAIN
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun-secret
                  key: MAILGUN_API_KEY
            - name: MAILGUN_SENDER
              valueFrom:
                secretKeyRef:
                  name: mailgun-secret
                  key: MAILGUN_SENDER
            - name: EMAIL_SIMULATION_MODE
              value: "false"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
